server:
  port: 8050

logging:
  level:
    my:
      finance:
        hackathon:
          app ${LOGGER_LEVEL:DEBUG}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  application:
    name: my-finance-vector

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      schema: finance_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS finance_schema
      connection-timeout: 10000
